[Interface]
Address = 10.99.0.1/24
ListenPort = 51820
PrivateKey = aLQ1sw6h23YgttZZDCioe+u6x7whLGtzy3/rgjPUr2E=
[Peer]
PublicKey = AOYuTFJxNWnfU7KUOmRWnqOYYtUV0ZVQ0BDnkEq7z08=
AllowedIPs = 10.99.0.2/32
